### ISSUE TITLE
Mudar para Organization page

### ISSUE THREAD

**Issue by rougeth** [pyladies-rp/pyladies-rp.github.io#1]
O site foi feito usando `Project site` do github pages, por isso que precisa do `/home` pra acessar a página (*home* é o nome desse projeto, funcionaria pra todos os outros projetos dentro da organização). 

Nessa página tem um helper que pode ajudar: https://help.github.com/articles/user-organization-and-project-pages/

A não ser que esse fosse o objetivo inicial, nesse caso, desconsiderem. :smile:

Parabéns pelo trabalho! :dancer:

**Comment by jtemporal** [comment]
mudança feita :+1:
